//
// Created by ozgur on 12/04/2024.
//

#ifndef FREEBOY_INSTRUCTION_H
#define FREEBOY_INSTRUCTION_H

#include <cstdint>
#include <string_view>
#include <array>

namespace gameboy
{
    struct Instruction
    {
        uint8_t length = 0u;
        uint8_t cycleCount = 0u;
        std::string_view mnemonic = "invalid";
    };

    static const std::array<Instruction, 0x100> standardInstructions
            {
                    // 0x0
                    Instruction{1, 4, "NOP"},
                    Instruction{3, 12, "LD BC,d16"},
                    Instruction{1, 8, "LD (BC),A"},
                    Instruction{1, 8, "INC BC"},
                    Instruction{1, 4, "INC B"},
                    Instruction{1, 4, "DEC B"},
                    Instruction{2, 8, "LD B,d8"},
                    Instruction{1, 4, "RLCA"},
                    Instruction{3, 20, "LD (a16),SP"},
                    Instruction{1, 8, "ADD HL,(BC)"},
                    Instruction{1, 8, "LD A,(BC)"},
                    Instruction{1, 8, "DEC BC"},
                    Instruction{1, 4, "INC C"},
                    Instruction{1, 4, "DEC C"},
                    Instruction{2, 8, "LD C, d8"},
                    Instruction{1, 4, "RRCA"},
                    // 0x1
                    Instruction{2, 4, "STOP 0"},
                    Instruction{3, 12, "LD DE,d16"},
                    Instruction{1, 8, "LD (DE),A"},
                    Instruction{1, 8, "INC DE"},
                    Instruction{1, 4, "INC D"},
                    Instruction{1, 4, "DEC D"},
                    Instruction{2, 8, "LD D,d8"},
                    Instruction{1, 4, "RLA"},
                    Instruction{2, 12, "JR r8"},
                    Instruction{1, 8, "ADD HL,DE"},
                    Instruction{1, 8, "LD A,(DE)"},
                    Instruction{1, 8, "DEC DE"},
                    Instruction{1, 4, "INC E"},
                    Instruction{1, 4, "DEC E"},
                    Instruction{2, 8, "LD E,d8"},
                    Instruction{1, 4, "RRA"},
                    // 0x2
                    Instruction{2, 12, "JR NZ,r8"},
                    Instruction{3, 12, "LD HL,d16"},
                    Instruction{1, 8, "LD (HL+),A"},
                    Instruction{1, 8, "INC HL"},
                    Instruction{1, 4, "INC H"},
                    Instruction{1, 4, "DEC H"},
                    Instruction{2, 8, "LD H,d8"},
                    Instruction{1, 4, "DAA"},
                    Instruction{2, 12, "JR Z,r8"},
                    Instruction{1, 8, "ADD HL,HL"},
                    Instruction{1, 8, "LD A,(HL+)"},
                    Instruction{1, 8, "DEC HL"},
                    Instruction{1, 4, "INC L"},
                    Instruction{1, 4, "DEC L"},
                    Instruction{2, 8, "LD L,d8"},
                    Instruction{1, 4, "CPL"},
                    // 0x3
                    Instruction{2, 12, "JR NC,r8"},
                    Instruction{3, 12, "LD SP,d16"},
                    Instruction{1, 8, "LD (HL-),A"},
                    Instruction{1, 8, "INC SP"},
                    Instruction{1, 12, "INC (HL)"},
                    Instruction{1, 12, "DEC (HL)"},
                    Instruction{2, 12, "LD (HL),d8"},
                    Instruction{1, 4, "SCF"},
                    Instruction{2, 12, "JR C,r8"},
                    Instruction{1, 8, "ADD HL,SP"},
                    Instruction{1, 8, "LD A,(HL-)"},
                    Instruction{1, 8, "DEC SP"},
                    Instruction{1, 4, "INC A"},
                    Instruction{1, 4, "DEC A"},
                    Instruction{2, 8, "LD A,d8"},
                    Instruction{1, 4, "CCF"},
                    // 0x4
                    Instruction{1, 4, "LD B,B"},
                    Instruction{1, 4, "LD B,C"},
                    Instruction{1, 4, "LD B,D"},
                    Instruction{1, 4, "LD B,E"},
                    Instruction{1, 4, "LD B,H"},
                    Instruction{1, 4, "LD B,L"},
                    Instruction{1, 8, "LD B,(HL)"},
                    Instruction{1, 4, "LD B,A"},
                    Instruction{1, 4, "LD C,B"},
                    Instruction{1, 4, "LD C,C"},
                    Instruction{1, 4, "LD C,D"},
                    Instruction{1, 4, "LD C,E"},
                    Instruction{1, 4, "LD C,H"},
                    Instruction{1, 4, "LD C,L"},
                    Instruction{1, 8, "LD C,(HL)"},
                    Instruction{1, 4, "LD C,A"},
                    // 0x5
                    Instruction{1, 4, "LD D,B"},
                    Instruction{1, 4, "LD D,C"},
                    Instruction{1, 4, "LD D,D"},
                    Instruction{1, 4, "LD D,E"},
                    Instruction{1, 4, "LD D,H"},
                    Instruction{1, 4, "LD D,L"},
                    Instruction{1, 8, "LD D,(HL)"},
                    Instruction{1, 4, "LD D,A"},
                    Instruction{1, 4, "LD E,B"},
                    Instruction{1, 4, "LD E,C"},
                    Instruction{1, 4, "LD E,D"},
                    Instruction{1, 4, "LD E,E"},
                    Instruction{1, 4, "LD E,H"},
                    Instruction{1, 4, "LD E,L"},
                    Instruction{1, 8, "LD E,(HL)"},
                    Instruction{1, 4, "LD E,A"},
                    // 0x6
                    Instruction{1, 4, "LD H,B"},
                    Instruction{1, 4, "LD H,C"},
                    Instruction{1, 4, "LD H,D"},
                    Instruction{1, 4, "LD H,E"},
                    Instruction{1, 4, "LD H,H"},
                    Instruction{1, 4, "LD H,L"},
                    Instruction{1, 8, "LD H,(HL)"},
                    Instruction{1, 4, "LD H,A"},
                    Instruction{1, 4, "LD L,B"},
                    Instruction{1, 4, "LD L,C"},
                    Instruction{1, 4, "LD L,D"},
                    Instruction{1, 4, "LD L,E"},
                    Instruction{1, 4, "LD L,H"},
                    Instruction{1, 4, "LD L,L"},
                    Instruction{1, 8, "LD L,(HL)"},
                    Instruction{1, 4, "LD L,A"},
                    // 0X7
                    Instruction{1, 8, "LD (HL),B"},
                    Instruction{1, 8, "LD (HL),C"},
                    Instruction{1, 8, "LD (HL),D"},
                    Instruction{1, 8, "LD (HL),E"},
                    Instruction{1, 8, "LD (HL),H"},
                    Instruction{1, 8, "LD (HL),L"},
                    Instruction{1, 4, "HALT"},
                    Instruction{1, 8, "LD (HL),A"},
                    Instruction{1, 4, "LD A,B"},
                    Instruction{1, 4, "LD A,C"},
                    Instruction{1, 4, "LD A,D"},
                    Instruction{1, 4, "LD A,E"},
                    Instruction{1, 4, "LD A,H"},
                    Instruction{1, 4, "LD A,L"},
                    Instruction{1, 8, "LD A,(HL)"},
                    Instruction{1, 4, "LD A,A"},
                    // 0X8
                    Instruction{1, 4, "ADD A,B"},
                    Instruction{1, 4, "ADD A,C"},
                    Instruction{1, 4, "ADD A,D"},
                    Instruction{1, 4, "ADD A,E"},
                    Instruction{1, 4, "ADD A,H"},
                    Instruction{1, 4, "ADD A,L"},
                    Instruction{1, 8, "ADD A,(HL)"},
                    Instruction{1, 4, "ADD A,A"},
                    Instruction{1, 4, "ADC A,B"},
                    Instruction{1, 4, "ADC A,C"},
                    Instruction{1, 4, "ADC A,D"},
                    Instruction{1, 4, "ADC A,E"},
                    Instruction{1, 4, "ADC A,H"},
                    Instruction{1, 4, "ADC A,L"},
                    Instruction{1, 8, "ADC A,(HL)"},
                    Instruction{1, 4, "ADC A,A"},
                    // 0X9
                    Instruction{1, 4, "SUB B"},
                    Instruction{1, 4, "SUB C"},
                    Instruction{1, 4, "SUB D"},
                    Instruction{1, 4, "SUB E"},
                    Instruction{1, 4, "SUB H"},
                    Instruction{1, 4, "SUB L"},
                    Instruction{1, 8, "SUB (HL)"},
                    Instruction{1, 4, "SUB A"},
                    Instruction{1, 4, "SBC A,B"},
                    Instruction{1, 4, "SBC A,C"},
                    Instruction{1, 4, "SBC A,D"},
                    Instruction{1, 4, "SBC A,E"},
                    Instruction{1, 4, "SBC A,H"},
                    Instruction{1, 4, "SBC A,L"},
                    Instruction{1, 8, "SBC A,(HL)"},
                    Instruction{1, 4, "SBC A,A"},
                    // 0XA
                    Instruction{1, 4, "AND B"},
                    Instruction{1, 4, "AND C"},
                    Instruction{1, 4, "AND D"},
                    Instruction{1, 4, "AND E"},
                    Instruction{1, 4, "AND H"},
                    Instruction{1, 4, "AND L"},
                    Instruction{1, 8, "AND (HL)"},
                    Instruction{1, 4, "AND A"},
                    Instruction{1, 4, "XOR B"},
                    Instruction{1, 4, "XOR C"},
                    Instruction{1, 4, "XOR D"},
                    Instruction{1, 4, "XOR E"},
                    Instruction{1, 4, "XOR H"},
                    Instruction{1, 4, "XOR L"},
                    Instruction{1, 8, "XOR (HL)"},
                    Instruction{1, 4, "XOR A"},
                    // 0XB
                    Instruction{1, 4, "OR B"},
                    Instruction{1, 4, "OR C"},
                    Instruction{1, 4, "OR D"},
                    Instruction{1, 4, "OR E"},
                    Instruction{1, 4, "OR H"},
                    Instruction{1, 4, "OR L"},
                    Instruction{1, 8, "OR (HL)"},
                    Instruction{1, 4, "OR A"},
                    Instruction{1, 4, "CP B"},
                    Instruction{1, 4, "CP C"},
                    Instruction{1, 4, "CP D"},
                    Instruction{1, 4, "CP E"},
                    Instruction{1, 4, "CP H"},
                    Instruction{1, 4, "CP L"},
                    Instruction{1, 8, "CP (HL)"},
                    Instruction{1, 4, "CP A"},
                    // 0XC
                    Instruction{1, 20, "RET NZ"},
                    Instruction{1, 12, "POP BC"},
                    Instruction{3, 16, "JP NZ,a16"},
                    Instruction{3, 16, "JP a16"},
                    Instruction{3, 24, "CALL NZ,a16"},
                    Instruction{1, 16, "PUSH BC"},
                    Instruction{2, 8, "ADD A,d8"},
                    Instruction{1, 16, "RST 00H"},
                    Instruction{1, 20, "RET Z"},
                    Instruction{1, 16, "RET"},
                    Instruction{3, 16, "JP Z,a16"},
                    Instruction{1, 4, "PREFIX CB"},
                    Instruction{3, 24, "CALL Z,a16"},
                    Instruction{3, 24, "CALL a16"},
                    Instruction{2, 8, "ADC A,d8"},
                    Instruction{1, 16, "RST 08H"},
                    // 0XD
                    Instruction{1, 20, "RET NC"},
                    Instruction{1, 12, "POP DE"},
                    Instruction{3, 12, "JP NC,a16"},
                    Instruction{},
                    Instruction{3, 24, "CALL NC,a16"},
                    Instruction{1, 16, "PUSH DE"},
                    Instruction{2, 8, "SUB d8"},
                    Instruction{1, 16, "RST 10H"},
                    Instruction{1, 20, "RET C"},
                    Instruction{1, 16, "RETI"},
                    Instruction{3, 16, "JP C,a16"},
                    Instruction{},
                    Instruction{3, 24, "CALL C,a16"},
                    Instruction{},
                    Instruction{2, 8, "SBC A,d8"},
                    Instruction{1, 16, "RST 18H"},
                    // 0XE
                    Instruction{2, 12, "LDH (a8),A"},
                    Instruction{1, 12, "POP HL"},
                    Instruction{2, 8, "LD (C),A"},
                    Instruction{},
                    Instruction{},
                    Instruction{1, 16, "PUSH HL"},
                    Instruction{2, 8, "AND d8"},
                    Instruction{1, 16, "RST 20H"},
                    Instruction{2, 16, "ADD SP,r8"},
                    Instruction{1, 4, "JP (HL)"},
                    Instruction{3, 16, "LD (a16),A"},
                    Instruction{},
                    Instruction{},
                    Instruction{},
                    Instruction{2, 8, "XOR d8"},
                    Instruction{1, 16, "RST 28H"},
                    // 0XF
                    Instruction{2, 12, "LDH A,(a8)"},
                    Instruction{1, 12, "POP AF"},
                    Instruction{2, 8, "LD A,(C)"},
                    Instruction{1, 4, "DI"},
                    Instruction{},
                    Instruction{1, 16, "PUSH AF"},
                    Instruction{2, 8, "OR d8"},
                    Instruction{1, 16, "RST 30H"},
                    Instruction{2, 12, "LD HL,SP+r8"},
                    Instruction{1, 8, "LD SP,HL"},
                    Instruction{3, 16, "LD A,(a16)"},
                    Instruction{1, 4, "EI"},
                    Instruction{},
                    Instruction{},
                    Instruction{2, 8, "CP d8"},
                    Instruction{1, 16, "RST 38H"},
            };

    static const std::array<Instruction, 0x100> extendedInstructions // CB instructions
            {
                    // 0x0
                    Instruction{2, 8, "RLC B"},
                    Instruction{2, 8, "RLC C"},
                    Instruction{2, 8, "RLC D"},
                    Instruction{2, 8, "RLC E"},
                    Instruction{2, 8, "RLC H"},
                    Instruction{2, 8, "RLC L"},
                    Instruction{2, 16, "RLC (HL)"},
                    Instruction{2, 8, "RLC A"},
                    Instruction{2, 8, "RRC B"},
                    Instruction{2, 8, "RRC C"},
                    Instruction{2, 8, "RRC D"},
                    Instruction{2, 8, "RRC E"},
                    Instruction{2, 8, "RRC H"},
                    Instruction{2, 8, "RRC L"},
                    Instruction{2, 16, "RRC (HL)"},
                    Instruction{2, 8, "RRC A"},
                    // 0x1
                    Instruction{2, 8, "RL B"},
                    Instruction{2, 8, "RL C"},
                    Instruction{2, 8, "RL D"},
                    Instruction{2, 8, "RL E"},
                    Instruction{2, 8, "RL H"},
                    Instruction{2, 8, "RL L"},
                    Instruction{2, 16, "RL (HL)"},
                    Instruction{2, 8, "RL A"},
                    Instruction{2, 8, "RR B"},
                    Instruction{2, 8, "RR C"},
                    Instruction{2, 8, "RR D"},
                    Instruction{2, 8, "RR E"},
                    Instruction{2, 8, "RR H"},
                    Instruction{2, 8, "RR L"},
                    Instruction{2, 16, "RR (HL)"},
                    Instruction{2, 8, "RR A"},
                    // 0x2
                    Instruction{2, 8, "SLA B"},
                    Instruction{2, 8, "SLA C"},
                    Instruction{2, 8, "SLA D"},
                    Instruction{2, 8, "SLA E"},
                    Instruction{2, 8, "SLA H"},
                    Instruction{2, 8, "SLA L"},
                    Instruction{2, 16, "SLA (HL)"},
                    Instruction{2, 8, "SLA A"},
                    Instruction{2, 8, "SRA B"},
                    Instruction{2, 8, "SRA C"},
                    Instruction{2, 8, "SRA D"},
                    Instruction{2, 8, "SRA E"},
                    Instruction{2, 8, "SRA H"},
                    Instruction{2, 8, "SRA L"},
                    Instruction{2, 16, "SRA (HL)"},
                    Instruction{2, 8, "SRA A"},
                    // 0x3
                    Instruction{2, 8, "SWAP B"},
                    Instruction{2, 8, "SWAP C"},
                    Instruction{2, 8, "SWAP D"},
                    Instruction{2, 8, "SWAP E"},
                    Instruction{2, 8, "SWAP H"},
                    Instruction{2, 8, "SWAP L"},
                    Instruction{2, 16, "SWAP (HL)"},
                    Instruction{2, 8, "SWAP A"},
                    Instruction{2, 8, "SRL B"},
                    Instruction{2, 8, "SRL C"},
                    Instruction{2, 8, "SRL D"},
                    Instruction{2, 8, "SRL E"},
                    Instruction{2, 8, "SRL H"},
                    Instruction{2, 8, "SRL L"},
                    Instruction{2, 16, "SRL (HL)"},
                    Instruction{2, 8, "SRL A"},
                    // 0x4
                    Instruction{2, 8, "BIT 0,B"},
                    Instruction{2, 8, "BIT 0,C"},
                    Instruction{2, 8, "BIT 0,D"},
                    Instruction{2, 8, "BIT 0,E"},
                    Instruction{2, 8, "BIT 0,H"},
                    Instruction{2, 8, "BIT 0,L"},
                    Instruction{2, 16, "BIT 0,(HL)"},
                    Instruction{2, 8, "BIT 0,A"},
                    Instruction{2, 8, "BIT 1,B"},
                    Instruction{2, 8, "BIT 1,C"},
                    Instruction{2, 8, "BIT 1,D"},
                    Instruction{2, 8, "BIT 1,E"},
                    Instruction{2, 8, "BIT 1,H"},
                    Instruction{2, 8, "BIT 1,L"},
                    Instruction{2, 16, "BIT 1,(HL)"},
                    Instruction{2, 8, "BIT 1,A"},
                    // 0x5
                    Instruction{2, 8, "BIT 2,B"},
                    Instruction{2, 8, "BIT 2,C"},
                    Instruction{2, 8, "BIT 2,D"},
                    Instruction{2, 8, "BIT 2,E"},
                    Instruction{2, 8, "BIT 2,H"},
                    Instruction{2, 8, "BIT 2,L"},
                    Instruction{2, 16, "BIT 2,(HL)"},
                    Instruction{2, 8, "BIT 2,A"},
                    Instruction{2, 8, "BIT 3,B"},
                    Instruction{2, 8, "BIT 3,C"},
                    Instruction{2, 8, "BIT 3,D"},
                    Instruction{2, 8, "BIT 3,E"},
                    Instruction{2, 8, "BIT 3,H"},
                    Instruction{2, 8, "BIT 3,L"},
                    Instruction{2, 16, "BIT 3,(HL)"},
                    Instruction{2, 8, "BIT 3,A"},
                    // 0x6
                    Instruction{2, 8, "BIT 4,B"},
                    Instruction{2, 8, "BIT 4,C"},
                    Instruction{2, 8, "BIT 4,D"},
                    Instruction{2, 8, "BIT 4,E"},
                    Instruction{2, 8, "BIT 4,H"},
                    Instruction{2, 8, "BIT 4,L"},
                    Instruction{2, 16, "BIT 4,(HL)"},
                    Instruction{2, 8, "BIT 4,A"},
                    Instruction{2, 8, "BIT 5,B"},
                    Instruction{2, 8, "BIT 5,C"},
                    Instruction{2, 8, "BIT 5,D"},
                    Instruction{2, 8, "BIT 5,E"},
                    Instruction{2, 8, "BIT 5,H"},
                    Instruction{2, 8, "BIT 5,L"},
                    Instruction{2, 16, "BIT 5,(HL)"},
                    Instruction{2, 8, "BIT 5,A"},
                    // 0X7
                    Instruction{2, 8, "BIT 6,B"},
                    Instruction{2, 8, "BIT 6,C"},
                    Instruction{2, 8, "BIT 6,D"},
                    Instruction{2, 8, "BIT 6,E"},
                    Instruction{2, 8, "BIT 6,H"},
                    Instruction{2, 8, "BIT 6,L"},
                    Instruction{2, 16, "BIT 6,(HL)"},
                    Instruction{2, 8, "BIT 6,A"},
                    Instruction{2, 8, "BIT 7,B"},
                    Instruction{2, 8, "BIT 7,C"},
                    Instruction{2, 8, "BIT 7,D"},
                    Instruction{2, 8, "BIT 7,E"},
                    Instruction{2, 8, "BIT 7,H"},
                    Instruction{2, 8, "BIT 7,L"},
                    Instruction{2, 16, "BIT 7,(HL)"},
                    Instruction{2, 8, "BIT 7,A"},
                    // 0X8
                    Instruction{2, 8, "RES 0,B"},
                    Instruction{2, 8, "RES 0,C"},
                    Instruction{2, 8, "RES 0,D"},
                    Instruction{2, 8, "RES 0,E"},
                    Instruction{2, 8, "RES 0,H"},
                    Instruction{2, 8, "RES 0,L"},
                    Instruction{2, 16, "RES 0,(HL)"},
                    Instruction{2, 8, "RES 0,A"},
                    Instruction{2, 8, "RES 1,B"},
                    Instruction{2, 8, "RES 1,C"},
                    Instruction{2, 8, "RES 1,D"},
                    Instruction{2, 8, "RES 1,E"},
                    Instruction{2, 8, "RES 1,H"},
                    Instruction{2, 8, "RES 1,L"},
                    Instruction{2, 16, "RES 1,(HL)"},
                    Instruction{2, 8, "RES 1,A"},
                    // 0X9
                    Instruction{2, 8, "RES 2,B"},
                    Instruction{2, 8, "RES 2,C"},
                    Instruction{2, 8, "RES 2,D"},
                    Instruction{2, 8, "RES 2,E"},
                    Instruction{2, 8, "RES 2,H"},
                    Instruction{2, 8, "RES 2,L"},
                    Instruction{2, 16, "RES 2,(HL)"},
                    Instruction{2, 8, "RES 2,A"},
                    Instruction{2, 8, "RES 3,B"},
                    Instruction{2, 8, "RES 3,C"},
                    Instruction{2, 8, "RES 3,D"},
                    Instruction{2, 8, "RES 3,E"},
                    Instruction{2, 8, "RES 3,H"},
                    Instruction{2, 8, "RES 3,L"},
                    Instruction{2, 16, "RES 3,(HL)"},
                    Instruction{2, 8, "RES 3,A"},
                    // 0x6
                    Instruction{2, 8, "RES 4,B"},
                    Instruction{2, 8, "RES 4,C"},
                    Instruction{2, 8, "RES 4,D"},
                    Instruction{2, 8, "RES 4,E"},
                    Instruction{2, 8, "RES 4,H"},
                    Instruction{2, 8, "RES 4,L"},
                    Instruction{2, 16, "RES 4,(HL)"},
                    Instruction{2, 8, "RES 4,A"},
                    Instruction{2, 8, "RES 5,B"},
                    Instruction{2, 8, "RES 5,C"},
                    Instruction{2, 8, "RES 5,D"},
                    Instruction{2, 8, "RES 5,E"},
                    Instruction{2, 8, "RES 5,H"},
                    Instruction{2, 8, "RES 5,L"},
                    Instruction{2, 16, "RES 5,(HL)"},
                    Instruction{2, 8, "RES 5,A"},
                    // 0X7
                    Instruction{2, 8, "RES 6,B"},
                    Instruction{2, 8, "RES 6,C"},
                    Instruction{2, 8, "RES 6,D"},
                    Instruction{2, 8, "RES 6,E"},
                    Instruction{2, 8, "RES 6,H"},
                    Instruction{2, 8, "RES 6,L"},
                    Instruction{2, 16, "RES 6,(HL)"},
                    Instruction{2, 8, "RES 6,A"},
                    Instruction{2, 8, "RES 7,B"},
                    Instruction{2, 8, "RES 7,C"},
                    Instruction{2, 8, "RES 7,D"},
                    Instruction{2, 8, "RES 7,E"},
                    Instruction{2, 8, "RES 7,H"},
                    Instruction{2, 8, "RES 7,L"},
                    Instruction{2, 16, "RES 7,(HL)"},
                    Instruction{2, 8, "RES 7,A"},
                    // 0XC
                    Instruction{2, 8, "SET 0,B"},
                    Instruction{2, 8, "SET 0,C"},
                    Instruction{2, 8, "SET 0,D"},
                    Instruction{2, 8, "SET 0,E"},
                    Instruction{2, 8, "SET 0,H"},
                    Instruction{2, 8, "SET 0,L"},
                    Instruction{2, 16, "SET 0,(HL)"},
                    Instruction{2, 8, "SET 0,A"},
                    Instruction{2, 8, "SET 1,B"},
                    Instruction{2, 8, "SET 1,C"},
                    Instruction{2, 8, "SET 1,D"},
                    Instruction{2, 8, "SET 1,E"},
                    Instruction{2, 8, "SET 1,H"},
                    Instruction{2, 8, "SET 1,L"},
                    Instruction{2, 16, "SET 1,(HL)"},
                    Instruction{2, 8, "SET 1,A"},
                    // 0X9
                    Instruction{2, 8, "SET 2,B"},
                    Instruction{2, 8, "SET 2,C"},
                    Instruction{2, 8, "SET 2,D"},
                    Instruction{2, 8, "SET 2,E"},
                    Instruction{2, 8, "SET 2,H"},
                    Instruction{2, 8, "SET 2,L"},
                    Instruction{2, 16, "SET 2,(HL)"},
                    Instruction{2, 8, "SET 2,A"},
                    Instruction{2, 8, "SET 3,B"},
                    Instruction{2, 8, "SET 3,C"},
                    Instruction{2, 8, "SET 3,D"},
                    Instruction{2, 8, "SET 3,E"},
                    Instruction{2, 8, "SET 3,H"},
                    Instruction{2, 8, "SET 3,L"},
                    Instruction{2, 16, "SET 3,(HL)"},
                    Instruction{2, 8, "SET 3,A"},
                    // 0x6
                    Instruction{2, 8, "SET 4,B"},
                    Instruction{2, 8, "SET 4,C"},
                    Instruction{2, 8, "SET 4,D"},
                    Instruction{2, 8, "SET 4,E"},
                    Instruction{2, 8, "SET 4,H"},
                    Instruction{2, 8, "SET 4,L"},
                    Instruction{2, 16, "SET 4,(HL)"},
                    Instruction{2, 8, "SET 4,A"},
                    Instruction{2, 8, "SET 5,B"},
                    Instruction{2, 8, "SET 5,C"},
                    Instruction{2, 8, "SET 5,D"},
                    Instruction{2, 8, "SET 5,E"},
                    Instruction{2, 8, "SET 5,H"},
                    Instruction{2, 8, "SET 5,L"},
                    Instruction{2, 16, "SET 5,(HL)"},
                    Instruction{2, 8, "SET 5,A"},
                    // 0X7
                    Instruction{2, 8, "SET 6,B"},
                    Instruction{2, 8, "SET 6,C"},
                    Instruction{2, 8, "SET 6,D"},
                    Instruction{2, 8, "SET 6,E"},
                    Instruction{2, 8, "SET 6,H"},
                    Instruction{2, 8, "SET 6,L"},
                    Instruction{2, 16, "SET 6,(HL)"},
                    Instruction{2, 8, "SET 6,A"},
                    Instruction{2, 8, "SET 7,B"},
                    Instruction{2, 8, "SET 7,C"},
                    Instruction{2, 8, "SET 7,D"},
                    Instruction{2, 8, "SET 7,E"},
                    Instruction{2, 8, "SET 7,H"},
                    Instruction{2, 8, "SET 7,L"},
                    Instruction{2, 16, "SET 7,(HL)"},
                    Instruction{2, 8, "SET 7,A"},
            };
}

#endif //FREEBOY_INSTRUCTION_H
